version: '3'

services:
  mysql-standalone:
    image: mysql:latest
    restart: always
    container_name: mysql-standalone
    environment:

      REDMINE_DB_MYSQL: 192.168.0.101
      REDMINE_DB_PORT: 3306
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: root
      REDMINE_DB_DATABASE: fullstack
  springboot-docker-container:
    image: springboot-docker-container
    container_name: springboot-docker-container
    ports:
      - 8080:8080
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysql-standalone